INSERT IGNORE INTO outfit (id, name, outfit_type, outfit_gender, created_at, modified_at)
VALUES
(1, '반팔티', 'TOP', 'UNISEX', NOW(), NOW()),
(2, '반바지', 'BOTTOM', 'UNISEX', NOW(), NOW()),
(3, '얇은 셔츠', 'TOP', 'UNISEX', NOW(), NOW()),
(4, '슬랙스', 'BOTTOM', 'UNISEX', NOW(), NOW()),
(5, '장우산', 'BASIC_UMBRELLA', 'UNISEX', NOW(), NOW()),
(6, '접이식 우산', 'FOLDING_UMBRELLA', 'UNISEX', NOW(), NOW()),
(8, '얇은 긴팔티', 'TOP', 'UNISEX', NOW(), NOW()),
(9, '얇은 가디건', 'TOP', 'UNISEX', NOW(), NOW()),
(10, '셔츠', 'TOP', 'UNISEX', NOW(), NOW()),
(11, '면바지', 'BOTTOM', 'UNISEX', NOW(), NOW()),
(12, '겉옷', 'LAYERED', 'UNISEX', NOW(), NOW()),
(13, '가디건', 'TOP', 'UNISEX', NOW(), NOW()),
(14, '얇은 자켓', 'TOP', 'UNISEX', NOW(), NOW()),
(15, '후드티', 'TOP', 'UNISEX', NOW(), NOW()),
(17, '자켓', 'TOP', 'UNISEX', NOW(), NOW()),
(19, '기모 후드티', 'TOP', 'UNISEX', NOW(), NOW()),
(20, '니트', 'TOP', 'UNISEX', NOW(), NOW()),
(22, '야상', 'TOP', 'UNISEX', NOW(), NOW()),
(23, '트렌치 코트', 'TOP', 'UNISEX', NOW(), NOW()),
(24, '코트', 'TOP', 'UNISEX', NOW(), NOW()),
(25, '가죽 자켓', 'TOP', 'UNISEX', NOW(), NOW()),
(26, '청바지', 'BOTTOM', 'UNISEX', NOW(), NOW()),
(28, '기모 바지', 'BOTTOM', 'UNISEX', NOW(), NOW()),
(29, '맨투맨', 'TOP', 'UNISEX', NOW(), NOW()),
(30, '스타킹', 'BOTTOM', 'FEMALE', NOW(), NOW()),
(31, '레깅스', 'BOTTOM', 'FEMALE', NOW(), NOW()),
(32, '긴팔티', 'TOP', 'UNISEX', NOW(), NOW());
