name: Java CD with Gradle

on:
  workflow_run:
    workflows: [ "Java CI with Gradle" ]
    types:
      - completed

permissions:
  contents: read

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 배포 타겟 설정
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" == "main" ]; then
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV

      - name: EC2 원격 접속 및 Docker compose
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.EC2_DEV_USERNAME }}
          host: ${{ secrets.EC2_DEV_HOST }}
          key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ env.DOCKERHUB_USERNAME }}/fashion-forecast-${{ env.DEPLOY_ENV }}:latest
            sudo docker compose -f docker-compose-${{ env.DEPLOY_ENV }}.yml down
            sudo docker compose -f docker-compose-${{ env.DEPLOY_ENV }}.yml up -d
            sudo docker image prune -f
