name: Java CD with Gradle

on:
  workflow_run:
    workflows: [ "Java CI with Gradle" ]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: EC2 원격 접속 및 Docker compose
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.EC2_DEV_USERNAME }}
          host: ${{ secrets.EC2_DEV_HOST }}
          key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
          script_stop: true
          ## 기존에 사용하지 않는 이미지 제거
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fashion-forecast-dev:latest
            sudo docker compose -f docker-compose-dev.yml down
            sudo docker compose -f docker-compose-dev.yml up -d
            sudo docker image prune -af
